# Autogenerated wrapper script for SHTnsKit_jll for x86_64-linux-gnu
export libshtns, libshtns_omp

using JLLWrappers

JLLWrappers.@generate_wrapper_header("SHTnsKit")
JLLWrappers.@declare_library_product(libshtns, "libshtns.so")
JLLWrappers.@declare_library_product(libshtns_omp, "libshtns_omp.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libshtns,
        "lib/libshtns.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )
    JLLWrappers.@init_library_product(
        libshtns_omp,
        "lib/libshtns_omp.so", 
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()