// This file was automatically generated by 'make' from file 'omp_spat_to_SH.gen.c'.
// To modify it, please consider modifying omp_spat_to_SH.gen.c
/*
 * Copyright (c) 2010-2020 Centre National de la Recherche Scientifique.
 * written by Nathanael Schaeffer (CNRS, ISTerre, Grenoble, France).
 * 
 * nathanael.schaeffer@univ-grenoble-alpes.fr
 * 
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software. You can use,
 * modify and/or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 * 
 */

//////////////////////////////////////////////////

	void GEN3(_an1,NWAY,SUFFIX)(shtns_cfg shtns, double *BrF, cplx *Qlm, const long int llim, const int im);
	void GEN3(_an1_hi,NWAY,SUFFIX)(shtns_cfg shtns, double *BrF, cplx *Qlm, const long int llim, const int im);


	static
	void GEN3(spat_to_SH_omp_a,NWAY,SUFFIX)(shtns_cfg shtns, double *Vr, cplx *Qlm, long int llim) {

	double *BrF;		// contains the Fourier transformed data
	unsigned imlim=0;

	BrF = Vr;
  #ifndef SHT_AXISYM
	imlim = MTR;
	#ifdef SHT_VAR_LTR
		if (imlim*MRES > (unsigned) llim) imlim = ((unsigned) llim)/MRES;		// 32bit mul and div should be faster
	#endif

	if (shtns->fft_mode != FFT_NONE) {
		if (shtns->fft_mode & FFT_OOP) {		// alloc memory for out-of-place FFT
			unsigned long nv = shtns->nspat;
			BrF = (double*) VMALLOC( nv * sizeof(double) );
		}
		if ((shtns->fft_mode & FFT_PHI_CONTIG_SPLIT) ==0) {
			fftw_execute_dft(shtns->fftc, ((cplx *) Vr), ((cplx *) BrF));
		} else {
			fftw_execute_split_dft(shtns->fftc, Vr+NPHI, Vr, BrF+1, BrF);
		}
	}
  #endif

	#pragma omp parallel num_threads(shtns->nthreads)
	{
		if (llim < SHT_L_RESCALE_FLY) {
			#pragma omp for schedule(dynamic,1) nowait
			for (int im=0; im<=imlim; im++) {
				for (int b=0; b<shtns->howmany; b++) {
					long spec_ofs = b * shtns->spec_dist;
					long spat_ofs = b * shtns->spat_dist;
					GEN3(_an1,NWAY,SUFFIX)(shtns, BrF+spat_ofs, Qlm+spec_ofs, llim, im);
				}
			}
		} else {
			#pragma omp for schedule(dynamic,1) nowait
			for (int im=0; im<=imlim; im++) {
				for (int b=0; b<shtns->howmany; b++) {
					long spec_ofs = b * shtns->spec_dist;
					long spat_ofs = b * shtns->spat_dist;
					GEN3(_an1_hi,NWAY,SUFFIX)(shtns, BrF+spat_ofs, Qlm+spec_ofs, llim, im);
				}
			}
		}
		#ifndef SHT_AXISYM
			if (imlim < MMAX) {		// zero out m > imlim
				long l = LiM(shtns, (imlim+1)*MRES, imlim+1);
				#pragma omp for schedule(dynamic,1) nowait
				for (int b=0; b<shtns->howmany; b++) {
					long spec_ofs = b * shtns->spec_dist;
					memset(Qlm+l+spec_ofs, 0, (shtns->nlm - l)*sizeof(cplx));
				}
			}
		#endif
	}

  #ifndef SHT_AXISYM
  	if (shtns->fft_mode & FFT_OOP) {		// free memory
	    VFREE(BrF);
	}
  #endif

  }

	static
	void GEN3(spat_to_SH_omp_b,NWAY,SUFFIX)(shtns_cfg shtns, double *Vr, cplx *Qlm, long int llim) {

	double *BrF;		// contains the Fourier transformed data
	unsigned imlim=0;

	BrF = Vr;
  #ifndef SHT_AXISYM
	imlim = MTR;
	#ifdef SHT_VAR_LTR
		if (imlim*MRES > (unsigned) llim) imlim = ((unsigned) llim)/MRES;		// 32bit mul and div should be faster
	#endif

	if (shtns->fft_mode & FFT_OOP) {		// alloc memory for out-of-place FFT
		unsigned long nv = shtns->nspat;
		BrF = (double*) VMALLOC( nv * sizeof(double) );
	}

	#pragma omp parallel num_threads(shtns->nthreads)
	{
		const int nblk = (NLAT/2) / shtns->nthreads;
		if ((shtns->fft_mode & FFT_PHI_CONTIG_SPLIT) == 0) {
			#pragma omp for schedule(dynamic) nowait
			for (int k=0; k<shtns->nthreads; k++)
				fftw_execute_dft(shtns->fftc_block, ((cplx *) Vr) + k*nblk, ((cplx *) BrF) + k*nblk);
		} else {
			#pragma omp for schedule(dynamic) nowait
			for (int k=0; k<shtns->nthreads; k++) 
				fftw_execute_split_dft(shtns->fftc_block, Vr+NPHI*(1+2*k*nblk), Vr+NPHI*2*k*nblk, BrF+1+NPHI*2*k*nblk, BrF+NPHI*2*k*nblk);
		}
		#pragma omp barrier
  #else
	#pragma omp parallel num_threads(shtns->nthreads)
	{
  #endif
		if (llim < SHT_L_RESCALE_FLY) {
			#pragma omp for schedule(dynamic,1) nowait
			for (int im=0; im <= imlim/2; im++) {
				GEN3(_an1,NWAY,SUFFIX)(shtns, BrF, Qlm, llim, im);
				if (imlim-im > im) {
					GEN3(_an1,NWAY,SUFFIX)(shtns, BrF, Qlm, llim, imlim-im);
				}
			}
		} else {
			#pragma omp for schedule(dynamic,1) nowait
			for (int im=0; im<=imlim; im++) {
				GEN3(_an1_hi,NWAY,SUFFIX)(shtns, BrF, Qlm, llim, im);
				if (imlim-im > im) {
					GEN3(_an1_hi,NWAY,SUFFIX)(shtns, BrF, Qlm, llim, imlim-im);
				}
			}
		}
		#ifndef SHT_AXISYM
			if (imlim < MMAX) {		// zero out m > imlim
				long l = LiM(shtns, (imlim+1)*MRES, imlim+1);
				#pragma omp single nowait
				memset(Qlm+l, 0, (shtns->nlm - l)*sizeof(cplx));
			}
		#endif
	}

  #ifndef SHT_AXISYM
  	if (shtns->fft_mode & FFT_OOP) {		// free memory
	    VFREE(BrF);
	}
  #endif
  }

	#undef LSPAN
