// This file was automatically generated by 'make' from file 'omp_spat_to_SH.gen.c'.
// To modify it, please consider modifying omp_spat_to_SH.gen.c
/*
 * Copyright (c) 2010-2020 Centre National de la Recherche Scientifique.
 * written by Nathanael Schaeffer (CNRS, ISTerre, Grenoble, France).
 * 
 * nathanael.schaeffer@univ-grenoble-alpes.fr
 * 
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software. You can use,
 * modify and/or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 * 
 */

//////////////////////////////////////////////////

	void GEN3(_an2,NWAY,SUFFIX)(shtns_cfg shtns, double *BtF, double *BpF, cplx *Slm, cplx *Tlm, const long int llim, const int im);
	void GEN3(_an2_hi,NWAY,SUFFIX)(shtns_cfg shtns, double *BtF, double *BpF, cplx *Slm, cplx *Tlm, const long int llim, const int im);


	static
	void GEN3(spat_to_SHsphtor_omp_a,NWAY,SUFFIX)(shtns_cfg shtns, double *Vt, double *Vp, cplx *Slm, cplx *Tlm, long int llim) {

	double *BtF, *BpF;	// contains the Fourier transformed data
	unsigned imlim=0;

	BtF = Vt;	BpF = Vp;
  #ifndef SHT_AXISYM
	imlim = MTR;
	#ifdef SHT_VAR_LTR
		if (imlim*MRES > (unsigned) llim) imlim = ((unsigned) llim)/MRES;		// 32bit mul and div should be faster
	#endif

	if (shtns->fft_mode != FFT_NONE) {
		if (shtns->fft_mode & FFT_OOP) {		// alloc memory for out-of-place FFT
			unsigned long nv = shtns->nspat;
			BtF = (double*) VMALLOC( 2*nv * sizeof(double) );
			BpF = BtF + nv;
		}
		if ((shtns->fft_mode & FFT_PHI_CONTIG_SPLIT) ==0) {
			fftw_execute_dft(shtns->fftc, ((cplx *) Vt), ((cplx *) BtF));
			fftw_execute_dft(shtns->fftc, ((cplx *) Vp), ((cplx *) BpF));
		} else {
			fftw_execute_split_dft(shtns->fftc, Vt+NPHI, Vt, BtF+1, BtF);
			fftw_execute_split_dft(shtns->fftc, Vp+NPHI, Vp, BpF+1, BpF);
		}
	}
  #endif

	#pragma omp parallel num_threads(shtns->nthreads)
	{
		if (llim < SHT_L_RESCALE_FLY) {
			#pragma omp for schedule(dynamic,1) nowait
			for (int im=0; im<=imlim; im++) {
				for (int b=0; b<shtns->howmany; b++) {
					long spec_ofs = b * shtns->spec_dist;
					long spat_ofs = b * shtns->spat_dist;
					GEN3(_an2,NWAY,SUFFIX)(shtns, BtF+spat_ofs, BpF+spat_ofs, Slm+spec_ofs, Tlm+spec_ofs, llim, im);
				}
			}
		} else {
			#pragma omp for schedule(dynamic,1) nowait
			for (int im=0; im<=imlim; im++) {
				for (int b=0; b<shtns->howmany; b++) {
					long spec_ofs = b * shtns->spec_dist;
					long spat_ofs = b * shtns->spat_dist;
					GEN3(_an2_hi,NWAY,SUFFIX)(shtns, BtF+spat_ofs, BpF+spat_ofs, Slm+spec_ofs, Tlm+spec_ofs, llim, im);
				}
			}
		}
		#ifndef SHT_AXISYM
			if (imlim < MMAX) {		// zero out m > imlim
				long l = LiM(shtns, (imlim+1)*MRES, imlim+1);
				#pragma omp for schedule(dynamic,1) nowait
				for (int b=0; b<shtns->howmany; b++) {
					long spec_ofs = b * shtns->spec_dist;
					memset(Slm+l+spec_ofs, 0, (shtns->nlm - l)*sizeof(cplx));
					memset(Tlm+l+spec_ofs, 0, (shtns->nlm - l)*sizeof(cplx));
				}
			}
		#endif
	}

  #ifndef SHT_AXISYM
  	if (shtns->fft_mode & FFT_OOP) {		// free memory
	    VFREE(BtF);	// this frees also BpF.
	}
  #endif

  }

	static
	void GEN3(spat_to_SHsphtor_omp_b,NWAY,SUFFIX)(shtns_cfg shtns, double *Vt, double *Vp, cplx *Slm, cplx *Tlm, long int llim) {

	double *BtF, *BpF;	// contains the Fourier transformed data
	unsigned imlim=0;

	BtF = Vt;	BpF = Vp;
  #ifndef SHT_AXISYM
	imlim = MTR;
	#ifdef SHT_VAR_LTR
		if (imlim*MRES > (unsigned) llim) imlim = ((unsigned) llim)/MRES;		// 32bit mul and div should be faster
	#endif

	if (shtns->fft_mode & FFT_OOP) {		// alloc memory for out-of-place FFT
		unsigned long nv = shtns->nspat;
		BtF = (double*) VMALLOC( 2*nv * sizeof(double) );
		BpF = BtF + nv;
	}

	#pragma omp parallel num_threads(shtns->nthreads)
	{
		const int nblk = (NLAT/2) / shtns->nthreads;
		if ((shtns->fft_mode & FFT_PHI_CONTIG_SPLIT) == 0) {
			#pragma omp for schedule(dynamic) nowait
			for (int k=0; k<shtns->nthreads; k++) 
				fftw_execute_dft(shtns->fftc_block, ((cplx *) Vt) + k*nblk, ((cplx *) BtF) + k*nblk);
			#pragma omp for schedule(dynamic) nowait
			for (int k=0; k<shtns->nthreads; k++) 
				fftw_execute_dft(shtns->fftc_block, ((cplx *) Vp) + k*nblk, ((cplx *) BpF) + k*nblk);
		} else {
			#pragma omp for schedule(dynamic) nowait
			for (int k=0; k<shtns->nthreads; k++) 
				fftw_execute_split_dft(shtns->fftc_block, Vt+NPHI*(1+2*k*nblk), Vt+NPHI*2*k*nblk, BtF+1+NPHI*2*k*nblk, BtF+NPHI*2*k*nblk);
			#pragma omp for schedule(dynamic) nowait
			for (int k=0; k<shtns->nthreads; k++) 
				fftw_execute_split_dft(shtns->fftc_block, Vp+NPHI*(1+2*k*nblk), Vp+NPHI*2*k*nblk, BpF+1+NPHI*2*k*nblk, BpF+NPHI*2*k*nblk);
		}
		#pragma omp barrier
  #else
	#pragma omp parallel num_threads(shtns->nthreads)
	{
  #endif
		if (llim < SHT_L_RESCALE_FLY) {
			#pragma omp for schedule(dynamic,1) nowait
			for (int im=0; im <= imlim/2; im++) {
				GEN3(_an2,NWAY,SUFFIX)(shtns, BtF, BpF, Slm, Tlm, llim, im);
				if (imlim-im > im) {
					GEN3(_an2,NWAY,SUFFIX)(shtns, BtF, BpF, Slm, Tlm, llim, imlim-im);
				}
			}
		} else {
			#pragma omp for schedule(dynamic,1) nowait
			for (int im=0; im<=imlim; im++) {
				GEN3(_an2_hi,NWAY,SUFFIX)(shtns, BtF, BpF, Slm, Tlm, llim, im);
				if (imlim-im > im) {
					GEN3(_an2_hi,NWAY,SUFFIX)(shtns, BtF, BpF, Slm, Tlm, llim, imlim-im);
				}
			}
		}
		#ifndef SHT_AXISYM
			if (imlim < MMAX) {		// zero out m > imlim
				long l = LiM(shtns, (imlim+1)*MRES, imlim+1);
				#pragma omp single nowait
				memset(Slm+l, 0, (shtns->nlm - l)*sizeof(cplx));
				#pragma omp single nowait
				memset(Tlm+l, 0, (shtns->nlm - l)*sizeof(cplx));
			}
		#endif
	}

  #ifndef SHT_AXISYM
  	if (shtns->fft_mode & FFT_OOP) {		// free memory
	    VFREE(BtF);	// this frees also BpF.
	}
  #endif
  }

	#undef LSPAN
