// This file was automatically generated by 'make' from file 'fly_spat_to_SH.gen.c'.
// To modify it, please consider modifying fly_spat_to_SH.gen.c
/*
 * Copyright (c) 2010-2024 Centre National de la Recherche Scientifique.
 * written by Nathanael Schaeffer (CNRS, ISTerre, Grenoble, France).
 * 
 * nathanael.schaeffer@univ-grenoble-alpes.fr
 * 
 * This software is governed by the CeCILL license under French law and
 * abiding by the rules of distribution of free software. You can use,
 * modify and/or redistribute the software under the terms of the CeCILL
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 * 
 */

//////////////////////////////////////////////////


	void GEN3(_an2,NWAY,_l)(shtns_cfg shtns, double *BtF, double *BpF, cplx *Slm, cplx *Tlm, const long int llim, const int imlim);
	void GEN3(_an2_hi,NWAY,_l)(shtns_cfg shtns, double *BtF, double *BpF, cplx *Slm, cplx *Tlm, const long int llim, const int imlim);


	static void GEN3(spat_to_SHsphtor_fly,NWAY,SUFFIX)(shtns_cfg shtns, double *Vt, double *Vp, cplx *Slm, cplx *Tlm, const long int llim) {


	double *BtF, *BpF;	// contains the Fourier transformed data
	unsigned imlim=0;

	BtF = Vt;	BpF = Vp;
  #ifndef SHT_AXISYM
	imlim = MTR;
	#ifdef SHT_VAR_LTR
		if (imlim*MRES > (unsigned) llim) imlim = ((unsigned) llim)/MRES;		// 32bit mul and div should be faster
	#endif
	if (shtns->fft_mode != FFT_NONE) {
		if (shtns->fft_mode & FFT_OOP) {		// alloc memory for out-of-place FFT
			unsigned long nv = shtns->nspat;
			BtF = (double*) VMALLOC( 2*nv * sizeof(double) );
			BpF = BtF + nv;
		}
	    if ((shtns->fft_mode & FFT_PHI_CONTIG_SPLIT) == 0) {	// regular FFT
			fftw_execute_dft(shtns->fftc,(cplx*)Vt, (cplx*)BtF);
			fftw_execute_dft(shtns->fftc,(cplx*)Vp, (cplx*)BpF);
		} else {	// split FFT
			fftw_execute_split_dft(shtns->fftc, Vt+NPHI, Vt, BtF+1, BtF);
			fftw_execute_split_dft(shtns->fftc, Vp+NPHI, Vp, BpF+1, BpF);
	    }
	}
  #endif

  #ifndef SHT_AXISYM
	if (llim >= SHT_L_RESCALE_FLY) {
		for (int im=0; im<=imlim; im++) {
			for (int b=0; b<shtns->howmany; b++) {
				long spec_ofs = b * shtns->spec_dist;
				long spat_ofs = b * shtns->spat_dist;
				GEN3(_an2_hi,NWAY,_l)(shtns, BtF+spat_ofs, BpF+spat_ofs, Slm+spec_ofs, Tlm+spec_ofs, llim, im);
			}
		}
	} else
  #endif
	{
		for (int im=0; im<=imlim; im++) {
			for (int b=0; b<shtns->howmany; b++) {
				long spec_ofs = b * shtns->spec_dist;
				long spat_ofs = b * shtns->spat_dist;
				GEN3(_an2,NWAY,_l)(shtns, BtF+spat_ofs, BpF+spat_ofs, Slm+spec_ofs, Tlm+spec_ofs, llim, im);
			}
		}
	}

  #ifndef SHT_AXISYM
	if (imlim < MMAX) {		// zero out m > imlim
		long l = LiM(shtns, (imlim+1)*MRES, imlim+1);
		for (int b=0; b<shtns->howmany; b++) {
			long spec_ofs = b * shtns->spec_dist;
			memset(Slm+l+spec_ofs, 0, (shtns->nlm - l)*sizeof(cplx));
			memset(Tlm+l+spec_ofs, 0, (shtns->nlm - l)*sizeof(cplx));
		}
	}
  	if (shtns->fft_mode & FFT_OOP) {		// free memory
	    VFREE(BtF);	// this frees also BpF.
	}
  #endif

  }


  #ifndef SHT_AXISYM

	static void GEN3(spat_to_SHsphtor_m_fly,NWAY,SUFFIX)(shtns_cfg shtns, int im, cplx *Vt, cplx *Vp, cplx *Slm, cplx *Tlm, long int llim) {

	double *alm, *al;
	double *wg, *ct, *st;
	double *l_2;
	long int nk, k, l,m;
	double alm0_rescale;
	int robert_form;
	rnd vw[4*llim+8];

	double ter[NLAT_2 + NWAY*VSIZE2] SSE;
	double tor[NLAT_2 + NWAY*VSIZE2] SSE;
	double per[NLAT_2 + NWAY*VSIZE2] SSE;
	double por[NLAT_2 + NWAY*VSIZE2] SSE;
	double tei[NLAT_2 + NWAY*VSIZE2] SSE;
	double toi[NLAT_2 + NWAY*VSIZE2] SSE;
	double pei[NLAT_2 + NWAY*VSIZE2] SSE;
	double poi[NLAT_2 + NWAY*VSIZE2] SSE;

	nk = NLAT_2;	// copy NLAT_2 to a local variable for faster access (inner loop limit)
	#if _GCC_VEC_
	  nk = ((unsigned) nk+(VSIZE2-1))/VSIZE2;
	#endif
	wg = shtns->wg;		ct = shtns->ct;		st = shtns->st;
	robert_form = shtns->robert_form;
	l_2 = shtns->l_2;

	for (k=nk*VSIZE2; k<(nk-1+NWAY)*VSIZE2; ++k) {
		ter[k] = 0.0;		tor[k] = 0.0;
		per[k] = 0.0;		por[k] = 0.0;
	}

	if (im == 0) {		// im=0
		alm = shtns->alm2;
		k=0;	do {	// compute symmetric and antisymmetric parts. (do not weight here, it is cheaper to weight y0)
			#ifndef SHTNS4MAGIC
			double n = creal(Vt[k]);		double s = creal(Vt[NLAT-1-k]);
			#else
			double n = creal(Vt[2*k]);		double s = creal(Vt[2*k+1]);
			#endif
			if (robert_form) {
				double st_1 = shtns->st_1[k];
				n *= st_1;		s *= st_1;
			}
			ter[k] = n+s;			tor[k] = n-s;
		} while(++k < nk*VSIZE2);
		k=0;	do {	// compute symmetric and antisymmetric parts. (do not weight here, it is cheaper to weight y0)
			#ifndef SHTNS4MAGIC
			double n = creal(Vp[k]);		double s = creal(Vp[NLAT-1-k]);
			#else
			double n = creal(Vp[2*k]);		double s = creal(Vp[2*k+1]);
			#endif
			if (robert_form) {
				double st_1 = shtns->st_1[k];
				n *= st_1;		s *= st_1;
			}
			per[k] = n+s;			por[k] = n-s;
		} while(++k < nk*VSIZE2);
		alm0_rescale = alm[0] * shtns->nphi;	// alm[0] takes into account the fftw normalization, *nphi cancels it
		Slm[0] = 0.0;		Tlm[0] = 0.0;		// l=0 is zero for the vector transform.
		k = 0;
		for (l=0;l<llim;++l) {
			vw[2*l] = vall(0.0);		vw[2*l+1] = vall(0.0);
		}
		do {
			al = alm;
			rnd cost[NWAY], y0[NWAY], y1[NWAY];
			rnd sint[NWAY], dy0[NWAY], dy1[NWAY];
			rnd terk[NWAY], tork[NWAY], perk[NWAY], pork[NWAY];
			for (int j=0; j<NWAY; ++j) {
				cost[j] = vread(ct, k+j);
				y0[j] = vall(alm0_rescale) * vread(wg, k+j);		// weight of Gauss quadrature appears here
				dy0[j] = vall(0.0);
				sint[j] = -vread(st, k+j);
				y1[j] =  (vall(al[1])*y0[j]) * cost[j];
				dy1[j] = (vall(al[1])*y0[j]) * sint[j];
				terk[j] = vread(ter, k+j);		tork[j] = vread(tor, k+j);
				perk[j] = vread(per, k+j);		pork[j] = vread(por, k+j);
			}
			al+=2;	l=1;
			while(l<llim) {
				for (int j=0; j<NWAY; ++j) {
					dy0[j] = vall(al[0])*(cost[j]*dy1[j] + y1[j]*sint[j]) + dy0[j];
					y0[j]  = vall(al[0])*(cost[j]*y1[j]) + y0[j];
				}
				for (int j=0; j<NWAY; ++j) {
					vw[2*l-2] += dy1[j] * terk[j];
					vw[2*l-1] -= dy1[j] * perk[j];
				}
				for (int j=0; j<NWAY; ++j) {
					dy1[j] = vall(al[1])*(cost[j]*dy0[j] + y0[j]*sint[j]) + dy1[j];
					y1[j]  = vall(al[1])*(cost[j]*y0[j]) + y1[j];
				}
				for (int j=0; j<NWAY; ++j) {
					vw[2*l]   += dy0[j] * tork[j];
					vw[2*l+1] -= dy0[j] * pork[j];
				}
				al+=2;	l+=2;
			}
			if (l==llim) {
				for (int j=0; j<NWAY; ++j) {
					vw[2*l-2] += dy1[j] * terk[j];
					vw[2*l-1] -= dy1[j] * perk[j];
				}
			}
			k+=NWAY;
		} while (k < nk);
		al = shtns->glm_analys;
		for (l=1; l<=llim; ++l) {
			#if _GCC_VEC_
				s2d a = vdup(al[l]);
				a *= vdup(l_2[l]);
				((v2d*)Slm)[l] = v2d_reduce(vw[2*l-2], vall(0)) * a;
				((v2d*)Tlm)[l] = v2d_reduce(vw[2*l-1], vall(0)) * a;
			#else
				double a = al[l];
				a *= l_2[l];	Slm[l] = vw[2*l-2]*a;		Tlm[l] = vw[2*l-1]*a;
			#endif
		}
		#ifdef SHT_VAR_LTR
			for (l=llim+1; l<= LMAX; ++l) {
				((v2d*)Slm)[l] = vdup(0.0);		((v2d*)Tlm)[l] = vdup(0.0);
			}
		#endif
		
	} else {		// im > 0
		const int ms = im*MRES;		// signed m.
		im = abs(im);			// positive im

		for (k=nk*VSIZE2; k<(nk-1+NWAY)*VSIZE2; ++k) {
			tei[k] = 0.0;		toi[k] = 0.0;
			pei[k] = 0.0;		poi[k] = 0.0;
		}

		m = im*MRES;
		l = shtns->tm[im] / VSIZE2;
		alm = shtns->alm2 + im*(LMAX+3) - (m*(im-1))/2;
		k = ((l*VSIZE2)>>1)*2;		// k must be even here.
		do {	// compute symmetric and antisymmetric parts.
			#ifndef SHTNS4MAGIC
			cplx n = Vt[k];			cplx s = Vt[NLAT-1-k];
			#else
			cplx n = Vt[2*k];	cplx s = Vt[2*k+1];
			#endif
			if (robert_form) {
				double st_1 = shtns->st_1[k];
				n *= st_1;		s *= st_1;
			}
			ter[k] = creal(n+s);	tei[k] = cimag(n+s);
			tor[k] = creal(n-s);	toi[k] = cimag(n-s);
		} while (++k<nk*VSIZE2);
		k = ((l*VSIZE2)>>1)*2;		// k must be even here.
		do {	// compute symmetric and antisymmetric parts.
			#ifndef SHTNS4MAGIC
			cplx n = Vp[k];			cplx s = Vp[NLAT-1-k];
			#else
			cplx n = Vp[2*k];	cplx s = Vp[2*k+1];
			#endif
			if (robert_form) {
				double st_1 = shtns->st_1[k];
				n *= st_1;		s *= st_1;
			}
			per[k] = creal(n+s);	pei[k] = cimag(n+s);
			por[k] = creal(n-s);	poi[k] = cimag(n-s);
		} while (++k<nk*VSIZE2);

		k=l;
		#if _GCC_VEC_
			rnd* v = vw;
		#else
			double* v = (double *) vw;
			double* t = (double *) vw;
		#endif
		for (l=llim+1-m; l>=0; l--) {
			v[0] = vall(0.0);		v[1] = vall(0.0);
			v[2] = vall(0.0);		v[3] = vall(0.0);		v+=4;
		}
		alm0_rescale = alm[0] * shtns->mpos_scale_analys * (shtns->nphi*2);		// handles real-norm
		do {
		#if _GCC_VEC_
			rnd* v = vw;
		#else
			double* v = (double *) vw;
			double* t = (double *) vw;
		#endif
			al = alm;
			rnd cost[NWAY], y0[NWAY], y1[NWAY];
			rnd terk[NWAY], teik[NWAY], tork[NWAY], toik[NWAY];
			rnd perk[NWAY], peik[NWAY], pork[NWAY], poik[NWAY];
			for (int j=0; j<NWAY; ++j) {
				cost[j] = vread(st, k+j);
				y0[j] = vall(1.0);
			}
			l=m-1;
			long int ny = 0;	// exponent to extend double precision range.
		if ((int)llim <= SHT_L_RESCALE_FLY) {
			do {		// sin(theta)^m
				if (l&1) for (int j=0; j<NWAY; ++j) y0[j] *= cost[j];
				for (int j=0; j<NWAY; ++j) cost[j] *= cost[j];
			} while(l >>= 1);
		} else {
			long int nsint = 0;
			do {		// sin(theta)^m		(use rescaling to avoid underflow)
				if (l&1) {
					for (int j=NWAY-1; j>=0; --j) y0[j] *= cost[j];
					ny += nsint;
					if (vlo(y0[NWAY-1]) < (SHT_ACCURACY+1.0/SHT_SCALE_FACTOR)) {
						ny--;
						for (int j=NWAY-1; j>=0; --j) y0[j] *= vall(SHT_SCALE_FACTOR);
					}
				}
				for (int j=NWAY-1; j>=0; --j) cost[j] *= cost[j];
				nsint += nsint;
				if (vlo(cost[NWAY-1]) < 1.0/SHT_SCALE_FACTOR) {
					nsint--;
					for (int j=NWAY-1; j>=0; --j) cost[j] *= vall(SHT_SCALE_FACTOR);
				}
			} while(l >>= 1);
		}
			for (int j=0; j<NWAY; ++j) {
				y0[j] *= vall(alm0_rescale);
				cost[j] = vread(ct, k+j);
				y1[j]  = (vall(al[1])*cost[j]) * y0[j];
			}
			l=m;	al+=2;
		  if (ny<0) {
			while (l<llim) {		// ylm treated as zero and ignored if ny < 0
				for (int j=0; j<NWAY; ++j) {
					y0[j] = (vall(al[0])*cost[j])*y1[j] + y0[j];
				}
				for (int j=0; j<NWAY; ++j) {
					y1[j] = (vall(al[1])*cost[j])*y0[j] + y1[j];
				}
				l+=2;	al+=2;
				if (fabs(vlo(y0[NWAY-1])) > SHT_ACCURACY*SHT_SCALE_FACTOR + 1.0) {		// rescale when value is significant
					for (int j=0; j<NWAY; ++j) {
						y0[j] *= vall(1.0/SHT_SCALE_FACTOR);		y1[j] *= vall(1.0/SHT_SCALE_FACTOR);
					}
					if (++ny == 0) break;
				}
			}
		  }
		  if LIKELY(ny == 0) {
			v+=4*(l-m);
			for (int j=0; j<NWAY; ++j) {	// prefetch
				y0[j] *= vread(wg, k+j);		y1[j] *= vread(wg, k+j);		// weight appears here (must be after the previous accuracy loop).
				terk[j] = vread( ter, k+j);		teik[j] = vread( tei, k+j);		tork[j] = vread( tor, k+j);		toik[j] = vread( toi, k+j);
				perk[j] = vread( per, k+j);		peik[j] = vread( pei, k+j);		pork[j] = vread( por, k+j);		poik[j] = vread( poi, k+j);
			}
			while (l<llim) {	// compute even and odd parts
				for (int j=0; j<NWAY; ++j)	{	v[0] += y0[j] * terk[j];	v[1] += y0[j] * teik[j];	}
				for (int j=0; j<NWAY; ++j)	{	v[2] += y0[j] * perk[j];	v[3] += y0[j] * peik[j];	}
				for (int j=0; j<NWAY; ++j) {
					y0[j] = (vall(al[0])*cost[j])*y1[j] + y0[j];
				}
				for (int j=0; j<NWAY; ++j)	{	v[4] += y1[j] * tork[j];	v[5] += y1[j] * toik[j];	}
				for (int j=0; j<NWAY; ++j)	{	v[6] += y1[j] * pork[j];	v[7] += y1[j] * poik[j];	}
				v+=8;
				for (int j=0; j<NWAY; ++j) {
					y1[j] = (vall(al[1])*cost[j])*y0[j] + y1[j];
				}
				l+=2;	al+=2;
			}
				for (int j=0; j<NWAY; ++j)	{	v[0] += y0[j] * terk[j];	v[1] += y0[j] * teik[j];	}
				for (int j=0; j<NWAY; ++j)	{	v[2] += y0[j] * perk[j];	v[3] += y0[j] * peik[j];	}
			if (l==llim) {
				for (int j=0; j<NWAY; ++j)	{	v[4] += y1[j] * tork[j];	v[5] += y1[j] * toik[j];	}
				for (int j=0; j<NWAY; ++j)	{	v[6] += y1[j] * pork[j];	v[7] += y1[j] * poik[j];	}
			}
		  }
			k+=NWAY;
		} while (k < nk);

		double* fl = shtns->glm_analys +  im*(LMAX+3) - (m*(im-1))/2;
		#if _GCC_VEC_
			for (long l=0; l<=llim-m; ++l) {
				((v2d*)vw)[2*l]   = v2d_reduce(vw[4*l],   vw[4*l+1]) * vdup(fl[l]);
				((v2d*)vw)[2*l+1] = v2d_reduce(vw[4*l+2], vw[4*l+3]) * vdup(fl[l]);
			}
			{	long l=llim-m+1;
				((v2d*)vw)[2*l]   = v2d_reduce(vw[4*l],   vw[4*l+1]) * vdup(fl[l]);
				((v2d*)vw)[2*l+1] = v2d_reduce(vw[4*l+2], vw[4*l+3]) * vdup(fl[l]);
			}
		#else
			for (long l=0; l<=llim-m; ++l) {
				((cplx*)vw)[2*l] *= fl[l];		((cplx*)vw)[2*l+1] *= fl[l];
			}
			{	long l=llim-m+1;
				((cplx*)vw)[2*l] *= fl[l];		((cplx*)vw)[2*l+1] *= fl[l];
			}
		#endif

		SH_2scal_to_vect(shtns->mx_van + 2*LM(shtns,m,m), l_2, llim, ms, (v2d*)vw, (v2d*)Slm, (v2d*)Tlm);

		#ifdef SHT_VAR_LTR
			for (long l=llim+1-m; l<=LMAX-m; ++l) {
				((v2d*)Slm)[l] = vdup(0.0);		((v2d*)Tlm)[l] = vdup(0.0);
			}
		#endif
	}

  }

  #endif
